---
# - import_playbook: mysql_setup_Centos7.yml
# - import_playbook: mysql_setup_Ubuntu.yml

# - import_playbook: install-apache.yml
# - import_playbook: weblab-setup.yml
#- import_playbook: weblab-update.yml         #chá»‰ upcode
 
####
#With Nginx
#- import_playbook: install-nginx.yml
- import_playbook: weblab-nginx-setup.yml